### ISSUE TITLE
System-wide default LANG setting in locale.conf

### ISSUE THREAD

**Issue by yuvadm** [debops/ansible-console#37]
While `en_US.UTF-8` is the only default locale installed system-wide, it is not *configured* to be used anywhere explicitly, leaving it up to the user to decide where to set `LANG=en_US.UTF-8` in their environment when required.

It might be useful to set this system-wide in advance via `/etc/locale.conf`, although this might have adverse effects in other scenarios.

A user who wishes to workaround this in the meantime can use `debops.resources` to set, for example:

```yaml
resources__host_files:
  - dest: '/etc/locale.conf'
    mode: '0644'
    content: |
      LANG=en_US.UTF-8
```
